# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbTriggerBoxx_UI.ui'
#
# Created: Fri Sep 20 17:08:01 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow_bbTriggerBoxx(object):
    def setupUi(self, MainWindow_bbTriggerBoxx):
        MainWindow_bbTriggerBoxx.setObjectName(_fromUtf8("MainWindow_bbTriggerBoxx"))
        MainWindow_bbTriggerBoxx.resize(713, 387)
        MainWindow_bbTriggerBoxx.setWindowTitle(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "ByteBoxx::TRIGGERBOXX control v1.01", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow_bbTriggerBoxx)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget_master = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_master.setObjectName(_fromUtf8("tabWidget_master"))
        self.tab_project = QtGui.QWidget()
        self.tab_project.setObjectName(_fromUtf8("tab_project"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_project)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_mesh = QtGui.QRadioButton(self.tab_project)
        self.radioButton_mesh.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Mesh Session", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_mesh.setObjectName(_fromUtf8("radioButton_mesh"))
        self.horizontalLayout_3.addWidget(self.radioButton_mesh)
        self.radioButton_texture = QtGui.QRadioButton(self.tab_project)
        self.radioButton_texture.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Texture Session", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_texture.setObjectName(_fromUtf8("radioButton_texture"))
        self.horizontalLayout_3.addWidget(self.radioButton_texture)
        spacerItem = QtGui.QSpacerItem(298, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.treeView_diskMap = QtGui.QTreeView(self.tab_project)
        self.treeView_diskMap.setEnabled(True)
        self.treeView_diskMap.setObjectName(_fromUtf8("treeView_diskMap"))
        self.verticalLayout.addWidget(self.treeView_diskMap)
        self.tabWidget_master.addTab(self.tab_project, _fromUtf8(""))
        self.tab_control = QtGui.QWidget()
        self.tab_control.setObjectName(_fromUtf8("tab_control"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_control)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.tab_control)
        self.label.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Subject:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_subject = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_subject.setReadOnly(True)
        self.lineEdit_subject.setObjectName(_fromUtf8("lineEdit_subject"))
        self.gridLayout.addWidget(self.lineEdit_subject, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_control)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Pose:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_pose = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_pose.setObjectName(_fromUtf8("lineEdit_pose"))
        self.gridLayout.addWidget(self.lineEdit_pose, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_control)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Root:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_photoDownload = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_photoDownload.setMinimumSize(QtCore.QSize(91, 0))
        self.lineEdit_photoDownload.setObjectName(_fromUtf8("lineEdit_photoDownload"))
        self.gridLayout.addWidget(self.lineEdit_photoDownload, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.tab_control)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Character:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_character = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_character.setReadOnly(True)
        self.lineEdit_character.setObjectName(_fromUtf8("lineEdit_character"))
        self.gridLayout_2.addWidget(self.lineEdit_character, 0, 1, 1, 3)
        self.label_5 = QtGui.QLabel(self.tab_control)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Current Tk:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.spinBox_take = QtGui.QSpinBox(self.tab_control)
        self.spinBox_take.setFrame(True)
        self.spinBox_take.setMinimum(1)
        self.spinBox_take.setObjectName(_fromUtf8("spinBox_take"))
        self.gridLayout_2.addWidget(self.spinBox_take, 1, 1, 1, 1)
        self.checkBox_inc = QtGui.QCheckBox(self.tab_control)
        self.checkBox_inc.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Auto Increment", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_inc.setChecked(True)
        self.checkBox_inc.setObjectName(_fromUtf8("checkBox_inc"))
        self.gridLayout_2.addWidget(self.checkBox_inc, 1, 2, 1, 2)
        self.label_10 = QtGui.QLabel(self.tab_control)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Img Wait (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.spinBox_imgWait = QtGui.QSpinBox(self.tab_control)
        self.spinBox_imgWait.setMaximum(500)
        self.spinBox_imgWait.setProperty("value", 0)
        self.spinBox_imgWait.setObjectName(_fromUtf8("spinBox_imgWait"))
        self.gridLayout_2.addWidget(self.spinBox_imgWait, 2, 1, 1, 1)
        self.checkBox_jpg = QtGui.QCheckBox(self.tab_control)
        self.checkBox_jpg.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "jpg", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_jpg.setChecked(False)
        self.checkBox_jpg.setObjectName(_fromUtf8("checkBox_jpg"))
        self.gridLayout_2.addWidget(self.checkBox_jpg, 2, 2, 1, 1)
        self.checkBox_cr2 = QtGui.QCheckBox(self.tab_control)
        self.checkBox_cr2.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "cr2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_cr2.setObjectName(_fromUtf8("checkBox_cr2"))
        self.gridLayout_2.addWidget(self.checkBox_cr2, 2, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab_control)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Definition:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_definition = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_definition.setText(_fromUtf8(""))
        self.lineEdit_definition.setReadOnly(True)
        self.lineEdit_definition.setObjectName(_fromUtf8("lineEdit_definition"))
        self.gridLayout_3.addWidget(self.lineEdit_definition, 0, 1, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(188, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 4)
        self.label_7 = QtGui.QLabel(self.tab_control)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Focus (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.doubleSpinBox_focus = QtGui.QDoubleSpinBox(self.tab_control)
        self.doubleSpinBox_focus.setFrame(True)
        self.doubleSpinBox_focus.setSingleStep(0.25)
        self.doubleSpinBox_focus.setObjectName(_fromUtf8("doubleSpinBox_focus"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_focus, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_control)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Flash (ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 2, 1, 1)
        self.doubleSpinBox_flash = QtGui.QDoubleSpinBox(self.tab_control)
        self.doubleSpinBox_flash.setFrame(True)
        self.doubleSpinBox_flash.setSingleStep(0.5)
        self.doubleSpinBox_flash.setObjectName(_fromUtf8("doubleSpinBox_flash"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_flash, 2, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_prime = QtGui.QPushButton(self.tab_control)
        self.pushButton_prime.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_prime.setFont(font)
        self.pushButton_prime.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Prime Array", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_prime.setObjectName(_fromUtf8("pushButton_prime"))
        self.horizontalLayout_2.addWidget(self.pushButton_prime)
        self.pushButton_fire = QtGui.QPushButton(self.tab_control)
        self.pushButton_fire.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_fire.setFont(font)
        self.pushButton_fire.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "&Fire Array", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_fire.setObjectName(_fromUtf8("pushButton_fire"))
        self.horizontalLayout_2.addWidget(self.pushButton_fire)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 3)
        self.plainTextEdit_logging = QtGui.QPlainTextEdit(self.tab_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_logging.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_logging.setSizePolicy(sizePolicy)
        self.plainTextEdit_logging.setReadOnly(True)
        self.plainTextEdit_logging.setObjectName(_fromUtf8("plainTextEdit_logging"))
        self.gridLayout_4.addWidget(self.plainTextEdit_logging, 2, 0, 1, 3)
        self.tabWidget_master.addTab(self.tab_control, _fromUtf8(""))
        self.tab_post = QtGui.QWidget()
        self.tab_post.setObjectName(_fromUtf8("tab_post"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_post)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.tab_post)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Placeholder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.tabWidget_master.addTab(self.tab_post, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget_master)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_logo = QtGui.QLabel(self.centralwidget)
        self.label_logo.setText(_fromUtf8(""))
        self.label_logo.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/bbTriggerBoxx_logo.jpg")))
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.horizontalLayout.addWidget(self.label_logo)
        spacerItem2 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow_bbTriggerBoxx.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_bbTriggerBoxx)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuNew_Session = QtGui.QMenu(self.menuFile)
        self.menuNew_Session.setTitle(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "New Session", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew_Session.setObjectName(_fromUtf8("menuNew_Session"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuComms = QtGui.QMenu(self.menubar)
        self.menuComms.setTitle(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Comms", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComms.setObjectName(_fromUtf8("menuComms"))
        self.menuSubject = QtGui.QMenu(self.menubar)
        self.menuSubject.setTitle(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSubject.setObjectName(_fromUtf8("menuSubject"))
        self.menuActive_Subject = QtGui.QMenu(self.menuSubject)
        self.menuActive_Subject.setTitle(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Active Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActive_Subject.setObjectName(_fromUtf8("menuActive_Subject"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow_bbTriggerBoxx.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow_bbTriggerBoxx)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow_bbTriggerBoxx.setStatusBar(self.statusbar)
        self.actionMesh = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionMesh.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMesh.setObjectName(_fromUtf8("actionMesh"))
        self.actionTexture = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionTexture.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Texture", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTexture.setObjectName(_fromUtf8("actionTexture"))
        self.actionConfigure = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionConfigure.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionOpen_COM1 = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionOpen_COM1.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Open COM1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_COM1.setObjectName(_fromUtf8("actionOpen_COM1"))
        self.actionCreate = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionCreate.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate.setObjectName(_fromUtf8("actionCreate"))
        self.actionLoad = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionTriggerBoxx = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionTriggerBoxx.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "TriggerBoxx", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTriggerBoxx.setObjectName(_fromUtf8("actionTriggerBoxx"))
        self.actionOpen_COM3 = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionOpen_COM3.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Open COM3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_COM3.setObjectName(_fromUtf8("actionOpen_COM3"))
        self.actionOpen_COM4 = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionOpen_COM4.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Open COM4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_COM4.setObjectName(_fromUtf8("actionOpen_COM4"))
        self.actionNew_Subject = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionNew_Subject.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "New Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Subject.setObjectName(_fromUtf8("actionNew_Subject"))
        self.actionNew_Character = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionNew_Character.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "New Character", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Character.setObjectName(_fromUtf8("actionNew_Character"))
        self.actionNew_Definition = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionNew_Definition.setText(QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "New Definition", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Definition.setObjectName(_fromUtf8("actionNew_Definition"))
        self.menuNew_Session.addAction(self.actionMesh)
        self.menuNew_Session.addAction(self.actionTexture)
        self.menuFile.addAction(self.menuNew_Session.menuAction())
        self.menuAbout.addAction(self.actionTriggerBoxx)
        self.menuComms.addAction(self.actionOpen_COM1)
        self.menuComms.addAction(self.actionOpen_COM3)
        self.menuComms.addAction(self.actionOpen_COM4)
        self.menuActive_Subject.addAction(self.actionNew_Character)
        self.menuActive_Subject.addAction(self.actionNew_Definition)
        self.menuSubject.addAction(self.actionNew_Subject)
        self.menuSubject.addAction(self.menuActive_Subject.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuComms.menuAction())
        self.menubar.addAction(self.menuSubject.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.label.setBuddy(self.lineEdit_subject)
        self.label_2.setBuddy(self.lineEdit_pose)
        self.label_6.setBuddy(self.lineEdit_photoDownload)
        self.label_3.setBuddy(self.lineEdit_character)
        self.label_5.setBuddy(self.spinBox_take)
        self.label_10.setBuddy(self.spinBox_imgWait)
        self.label_4.setBuddy(self.lineEdit_definition)
        self.label_7.setBuddy(self.doubleSpinBox_focus)
        self.label_8.setBuddy(self.doubleSpinBox_flash)

        self.retranslateUi(MainWindow_bbTriggerBoxx)
        self.tabWidget_master.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_bbTriggerBoxx)

    def retranslateUi(self, MainWindow_bbTriggerBoxx):
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_project), QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Project Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_control), QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Rig Control", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_post), QtGui.QApplication.translate("MainWindow_bbTriggerBoxx", "Post Process", None, QtGui.QApplication.UnicodeUTF8))

import bbTriggerBoxx_QRC_rc
