# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbTriggerBoxx_UI.ui'
#
# Created: Sun Mar 16 09:51:22 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_bbTriggerBoxx(object):
    def setupUi(self, MainWindow_bbTriggerBoxx):
        MainWindow_bbTriggerBoxx.setObjectName(_fromUtf8("MainWindow_bbTriggerBoxx"))
        MainWindow_bbTriggerBoxx.resize(848, 467)
        self.centralwidget = QtGui.QWidget(MainWindow_bbTriggerBoxx)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget_master = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_master.setObjectName(_fromUtf8("tabWidget_master"))
        self.tab_project = QtGui.QWidget()
        self.tab_project.setObjectName(_fromUtf8("tab_project"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_project)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_mesh = QtGui.QRadioButton(self.tab_project)
        self.radioButton_mesh.setObjectName(_fromUtf8("radioButton_mesh"))
        self.horizontalLayout_3.addWidget(self.radioButton_mesh)
        self.radioButton_texture = QtGui.QRadioButton(self.tab_project)
        self.radioButton_texture.setObjectName(_fromUtf8("radioButton_texture"))
        self.horizontalLayout_3.addWidget(self.radioButton_texture)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_6 = QtGui.QLabel(self.tab_project)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lineEdit_photoDownload = QtGui.QLineEdit(self.tab_project)
        self.lineEdit_photoDownload.setObjectName(_fromUtf8("lineEdit_photoDownload"))
        self.horizontalLayout_3.addWidget(self.lineEdit_photoDownload)
        spacerItem1 = QtGui.QSpacerItem(278, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.treeView_diskMap = QtGui.QTreeView(self.tab_project)
        self.treeView_diskMap.setEnabled(True)
        self.treeView_diskMap.setObjectName(_fromUtf8("treeView_diskMap"))
        self.verticalLayout.addWidget(self.treeView_diskMap)
        self.tabWidget_master.addTab(self.tab_project, _fromUtf8(""))
        self.tab_control = QtGui.QWidget()
        self.tab_control.setObjectName(_fromUtf8("tab_control"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_control)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_setcap = QtGui.QGroupBox(self.tab_control)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_setcap.setFont(font)
        self.groupBox_setcap.setCheckable(True)
        self.groupBox_setcap.setChecked(False)
        self.groupBox_setcap.setObjectName(_fromUtf8("groupBox_setcap"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_setcap)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox_setcap)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_subject = QtGui.QLineEdit(self.groupBox_setcap)
        self.lineEdit_subject.setReadOnly(True)
        self.lineEdit_subject.setObjectName(_fromUtf8("lineEdit_subject"))
        self.gridLayout.addWidget(self.lineEdit_subject, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_setcap)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEdit_character = QtGui.QLineEdit(self.groupBox_setcap)
        self.lineEdit_character.setReadOnly(True)
        self.lineEdit_character.setObjectName(_fromUtf8("lineEdit_character"))
        self.gridLayout.addWidget(self.lineEdit_character, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_setcap)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_definition = QtGui.QLineEdit(self.groupBox_setcap)
        self.lineEdit_definition.setText(_fromUtf8(""))
        self.lineEdit_definition.setReadOnly(True)
        self.lineEdit_definition.setObjectName(_fromUtf8("lineEdit_definition"))
        self.gridLayout.addWidget(self.lineEdit_definition, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_setcap)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.lineEdit_pose = QtGui.QLineEdit(self.groupBox_setcap)
        self.lineEdit_pose.setObjectName(_fromUtf8("lineEdit_pose"))
        self.gridLayout.addWidget(self.lineEdit_pose, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_setcap, 0, 0, 1, 2)
        self.groupBox_flexcap = QtGui.QGroupBox(self.tab_control)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_flexcap.setFont(font)
        self.groupBox_flexcap.setCheckable(True)
        self.groupBox_flexcap.setObjectName(_fromUtf8("groupBox_flexcap"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_flexcap)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.groupBox_flexcap)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_bucket = QtGui.QLineEdit(self.groupBox_flexcap)
        self.lineEdit_bucket.setObjectName(_fromUtf8("lineEdit_bucket"))
        self.gridLayout_2.addWidget(self.lineEdit_bucket, 0, 1, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_flexcap)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_flexcap, 0, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_control)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.doubleSpinBox_focus = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_focus.setFrame(True)
        self.doubleSpinBox_focus.setSingleStep(0.25)
        self.doubleSpinBox_focus.setObjectName(_fromUtf8("doubleSpinBox_focus"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_focus)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.doubleSpinBox_flash = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_flash.setFrame(True)
        self.doubleSpinBox_flash.setSingleStep(0.5)
        self.doubleSpinBox_flash.setObjectName(_fromUtf8("doubleSpinBox_flash"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_flash)
        self.checkBox_jpg = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_jpg.setChecked(True)
        self.checkBox_jpg.setObjectName(_fromUtf8("checkBox_jpg"))
        self.horizontalLayout_2.addWidget(self.checkBox_jpg)
        self.checkBox_cr2 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_cr2.setChecked(True)
        self.checkBox_cr2.setObjectName(_fromUtf8("checkBox_cr2"))
        self.horizontalLayout_2.addWidget(self.checkBox_cr2)
        self.gridLayout_3.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_control)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox_take = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_take.setFrame(True)
        self.spinBox_take.setMinimum(1)
        self.spinBox_take.setObjectName(_fromUtf8("spinBox_take"))
        self.horizontalLayout_5.addWidget(self.spinBox_take)
        self.checkBox_inc = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_inc.setChecked(True)
        self.checkBox_inc.setObjectName(_fromUtf8("checkBox_inc"))
        self.horizontalLayout_5.addWidget(self.checkBox_inc)
        spacerItem2 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.lineEdit_comment = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_comment.setText(_fromUtf8(""))
        self.lineEdit_comment.setReadOnly(False)
        self.lineEdit_comment.setObjectName(_fromUtf8("lineEdit_comment"))
        self.horizontalLayout_5.addWidget(self.lineEdit_comment)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 1, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_prime = QtGui.QPushButton(self.tab_control)
        self.pushButton_prime.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_prime.setFont(font)
        self.pushButton_prime.setObjectName(_fromUtf8("pushButton_prime"))
        self.horizontalLayout_4.addWidget(self.pushButton_prime)
        self.pushButton_fire = QtGui.QPushButton(self.tab_control)
        self.pushButton_fire.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_fire.setFont(font)
        self.pushButton_fire.setObjectName(_fromUtf8("pushButton_fire"))
        self.horizontalLayout_4.addWidget(self.pushButton_fire)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.groupBox = QtGui.QGroupBox(self.tab_control)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plainTextEdit_logging = QtGui.QPlainTextEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_logging.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_logging.setSizePolicy(sizePolicy)
        self.plainTextEdit_logging.setReadOnly(True)
        self.plainTextEdit_logging.setObjectName(_fromUtf8("plainTextEdit_logging"))
        self.verticalLayout_2.addWidget(self.plainTextEdit_logging)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tabWidget_master.addTab(self.tab_control, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget_master)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_logo = QtGui.QLabel(self.centralwidget)
        self.label_logo.setText(_fromUtf8(""))
        self.label_logo.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/bbTriggerBoxx_logo.jpg")))
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.horizontalLayout.addWidget(self.label_logo)
        spacerItem3 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow_bbTriggerBoxx.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_bbTriggerBoxx)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuNew_Session = QtGui.QMenu(self.menuFile)
        self.menuNew_Session.setObjectName(_fromUtf8("menuNew_Session"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuComms = QtGui.QMenu(self.menubar)
        self.menuComms.setObjectName(_fromUtf8("menuComms"))
        self.menuSubject = QtGui.QMenu(self.menubar)
        self.menuSubject.setObjectName(_fromUtf8("menuSubject"))
        self.menuActive_Subject = QtGui.QMenu(self.menuSubject)
        self.menuActive_Subject.setObjectName(_fromUtf8("menuActive_Subject"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuCopy = QtGui.QMenu(self.menubar)
        self.menuCopy.setObjectName(_fromUtf8("menuCopy"))
        MainWindow_bbTriggerBoxx.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow_bbTriggerBoxx)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow_bbTriggerBoxx.setStatusBar(self.statusbar)
        self.actionMesh = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionMesh.setObjectName(_fromUtf8("actionMesh"))
        self.actionTexture = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionTexture.setObjectName(_fromUtf8("actionTexture"))
        self.actionConfigure = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionOpen_COM1 = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionOpen_COM1.setObjectName(_fromUtf8("actionOpen_COM1"))
        self.actionCreate = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionCreate.setObjectName(_fromUtf8("actionCreate"))
        self.actionLoad = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionTriggerBoxx = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionTriggerBoxx.setObjectName(_fromUtf8("actionTriggerBoxx"))
        self.actionOpen_COM3 = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionOpen_COM3.setObjectName(_fromUtf8("actionOpen_COM3"))
        self.actionOpen_COM4 = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionOpen_COM4.setObjectName(_fromUtf8("actionOpen_COM4"))
        self.actionNew_Subject = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionNew_Subject.setObjectName(_fromUtf8("actionNew_Subject"))
        self.actionNew_Character = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionNew_Character.setObjectName(_fromUtf8("actionNew_Character"))
        self.actionNew_Definition = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionNew_Definition.setObjectName(_fromUtf8("actionNew_Definition"))
        self.actionEdit_Prefs = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionEdit_Prefs.setObjectName(_fromUtf8("actionEdit_Prefs"))
        self.actionStart_Monitor = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionStart_Monitor.setObjectName(_fromUtf8("actionStart_Monitor"))
        self.actionCopyNow = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionCopyNow.setObjectName(_fromUtf8("actionCopyNow"))
        self.actionLoad_Session = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionLoad_Session.setObjectName(_fromUtf8("actionLoad_Session"))
        self.actionHelp_on_TriggerBoxx = QtGui.QAction(MainWindow_bbTriggerBoxx)
        self.actionHelp_on_TriggerBoxx.setObjectName(_fromUtf8("actionHelp_on_TriggerBoxx"))
        self.menuNew_Session.addAction(self.actionMesh)
        self.menuNew_Session.addAction(self.actionTexture)
        self.menuFile.addAction(self.menuNew_Session.menuAction())
        self.menuFile.addAction(self.actionLoad_Session)
        self.menuFile.addAction(self.actionEdit_Prefs)
        self.menuAbout.addAction(self.actionTriggerBoxx)
        self.menuComms.addAction(self.actionOpen_COM1)
        self.menuComms.addAction(self.actionOpen_COM3)
        self.menuComms.addAction(self.actionOpen_COM4)
        self.menuActive_Subject.addAction(self.actionNew_Character)
        self.menuActive_Subject.addAction(self.actionNew_Definition)
        self.menuSubject.addAction(self.actionNew_Subject)
        self.menuSubject.addAction(self.menuActive_Subject.menuAction())
        self.menuHelp.addAction(self.actionHelp_on_TriggerBoxx)
        self.menuCopy.addAction(self.actionCopyNow)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCopy.menuAction())
        self.menubar.addAction(self.menuComms.menuAction())
        self.menubar.addAction(self.menuSubject.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.label.setBuddy(self.lineEdit_subject)
        self.label_3.setBuddy(self.lineEdit_character)
        self.label_4.setBuddy(self.lineEdit_definition)
        self.label_2.setBuddy(self.lineEdit_pose)
        self.label_7.setBuddy(self.doubleSpinBox_focus)
        self.label_8.setBuddy(self.doubleSpinBox_flash)
        self.label_5.setBuddy(self.spinBox_take)
        self.label_9.setBuddy(self.lineEdit_comment)

        self.retranslateUi(MainWindow_bbTriggerBoxx)
        self.tabWidget_master.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_bbTriggerBoxx)

    def retranslateUi(self, MainWindow_bbTriggerBoxx):
        MainWindow_bbTriggerBoxx.setWindowTitle(_translate("MainWindow_bbTriggerBoxx", "ByteBoxx::TRIGGERBOXX control v2.0 2014032", None))
        self.radioButton_mesh.setText(_translate("MainWindow_bbTriggerBoxx", "Mesh Session", None))
        self.radioButton_texture.setText(_translate("MainWindow_bbTriggerBoxx", "Texture Session", None))
        self.label_6.setText(_translate("MainWindow_bbTriggerBoxx", "Photo Download Drive:", None))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_project), _translate("MainWindow_bbTriggerBoxx", "Project Setup", None))
        self.groupBox_setcap.setTitle(_translate("MainWindow_bbTriggerBoxx", "Set Capture", None))
        self.label.setText(_translate("MainWindow_bbTriggerBoxx", "1.Subject:", None))
        self.label_3.setText(_translate("MainWindow_bbTriggerBoxx", "2.Character:", None))
        self.label_4.setText(_translate("MainWindow_bbTriggerBoxx", "3.Definition:", None))
        self.label_2.setText(_translate("MainWindow_bbTriggerBoxx", "4.Pose:", None))
        self.groupBox_flexcap.setTitle(_translate("MainWindow_bbTriggerBoxx", "Flex Capture", None))
        self.label_10.setText(_translate("MainWindow_bbTriggerBoxx", "Bucket:", None))
        self.groupBox_4.setTitle(_translate("MainWindow_bbTriggerBoxx", "Settings", None))
        self.label_7.setText(_translate("MainWindow_bbTriggerBoxx", "Focus (s):", None))
        self.label_8.setText(_translate("MainWindow_bbTriggerBoxx", "Flash (ms):", None))
        self.checkBox_jpg.setText(_translate("MainWindow_bbTriggerBoxx", "jpg", None))
        self.checkBox_cr2.setText(_translate("MainWindow_bbTriggerBoxx", "cr2", None))
        self.groupBox_5.setTitle(_translate("MainWindow_bbTriggerBoxx", "Take Info", None))
        self.label_5.setText(_translate("MainWindow_bbTriggerBoxx", "Current Tk:", None))
        self.checkBox_inc.setText(_translate("MainWindow_bbTriggerBoxx", "Auto Increment", None))
        self.label_9.setText(_translate("MainWindow_bbTriggerBoxx", "Comment:", None))
        self.pushButton_prime.setText(_translate("MainWindow_bbTriggerBoxx", "Prime Array", None))
        self.pushButton_fire.setText(_translate("MainWindow_bbTriggerBoxx", "&Fire Array", None))
        self.groupBox.setTitle(_translate("MainWindow_bbTriggerBoxx", "Logging", None))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_control), _translate("MainWindow_bbTriggerBoxx", "Rig Control", None))
        self.menuFile.setTitle(_translate("MainWindow_bbTriggerBoxx", "File", None))
        self.menuNew_Session.setTitle(_translate("MainWindow_bbTriggerBoxx", "New Session", None))
        self.menuAbout.setTitle(_translate("MainWindow_bbTriggerBoxx", "About", None))
        self.menuComms.setTitle(_translate("MainWindow_bbTriggerBoxx", "Comms", None))
        self.menuSubject.setTitle(_translate("MainWindow_bbTriggerBoxx", "Subject", None))
        self.menuActive_Subject.setTitle(_translate("MainWindow_bbTriggerBoxx", "Active Subject", None))
        self.menuHelp.setTitle(_translate("MainWindow_bbTriggerBoxx", "Help", None))
        self.menuCopy.setTitle(_translate("MainWindow_bbTriggerBoxx", "Copy", None))
        self.actionMesh.setText(_translate("MainWindow_bbTriggerBoxx", "Mesh", None))
        self.actionTexture.setText(_translate("MainWindow_bbTriggerBoxx", "Texture", None))
        self.actionConfigure.setText(_translate("MainWindow_bbTriggerBoxx", "Configure", None))
        self.actionOpen_COM1.setText(_translate("MainWindow_bbTriggerBoxx", "Open COM1", None))
        self.actionCreate.setText(_translate("MainWindow_bbTriggerBoxx", "Create", None))
        self.actionLoad.setText(_translate("MainWindow_bbTriggerBoxx", "Load", None))
        self.actionTriggerBoxx.setText(_translate("MainWindow_bbTriggerBoxx", "TriggerBoxx", None))
        self.actionOpen_COM3.setText(_translate("MainWindow_bbTriggerBoxx", "Open COM3", None))
        self.actionOpen_COM4.setText(_translate("MainWindow_bbTriggerBoxx", "Open COM4", None))
        self.actionNew_Subject.setText(_translate("MainWindow_bbTriggerBoxx", "New Subject", None))
        self.actionNew_Character.setText(_translate("MainWindow_bbTriggerBoxx", "New Character", None))
        self.actionNew_Definition.setText(_translate("MainWindow_bbTriggerBoxx", "New Definition", None))
        self.actionEdit_Prefs.setText(_translate("MainWindow_bbTriggerBoxx", "Edit Prefs", None))
        self.actionStart_Monitor.setText(_translate("MainWindow_bbTriggerBoxx", "Start Monitor", None))
        self.actionCopyNow.setText(_translate("MainWindow_bbTriggerBoxx", "CopyNow", None))
        self.actionLoad_Session.setText(_translate("MainWindow_bbTriggerBoxx", "Load Session", None))
        self.actionHelp_on_TriggerBoxx.setText(_translate("MainWindow_bbTriggerBoxx", "Help on TriggerBoxx", None))

import bbTriggerBoxx_QRC_rc
