# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbRenderBoxx_Proto_UI.ui'
#
# Created: Wed Sep 03 13:32:18 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_RenderBoxx(object):
    def setupUi(self, MainWindow_RenderBoxx):
        MainWindow_RenderBoxx.setObjectName(_fromUtf8("MainWindow_RenderBoxx"))
        MainWindow_RenderBoxx.resize(548, 435)
        self.centralwidget = QtGui.QWidget(MainWindow_RenderBoxx)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeView_diskmap = QtGui.QTreeView(self.tab)
        self.treeView_diskmap.setObjectName(_fromUtf8("treeView_diskmap"))
        self.verticalLayout.addWidget(self.treeView_diskmap)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.listWidget_queue = QtGui.QListWidget(self.tab)
        self.listWidget_queue.setMaximumSize(QtCore.QSize(16777215, 125))
        self.listWidget_queue.setObjectName(_fromUtf8("listWidget_queue"))
        self.verticalLayout.addWidget(self.listWidget_queue)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_add = QtGui.QPushButton(self.tab)
        self.pushButton_add.setObjectName(_fromUtf8("pushButton_add"))
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.pushButton_remove = QtGui.QPushButton(self.tab)
        self.pushButton_remove.setObjectName(_fromUtf8("pushButton_remove"))
        self.horizontalLayout.addWidget(self.pushButton_remove)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.checkBox_useMaya = QtGui.QCheckBox(self.tab_2)
        self.checkBox_useMaya.setChecked(True)
        self.checkBox_useMaya.setObjectName(_fromUtf8("checkBox_useMaya"))
        self.horizontalLayout_2.addWidget(self.checkBox_useMaya)
        self.lineEdit_fileLighting = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_fileLighting.setObjectName(_fromUtf8("lineEdit_fileLighting"))
        self.horizontalLayout_2.addWidget(self.lineEdit_fileLighting)
        self.pushButton_browseLight = QtGui.QPushButton(self.tab_2)
        self.pushButton_browseLight.setObjectName(_fromUtf8("pushButton_browseLight"))
        self.horizontalLayout_2.addWidget(self.pushButton_browseLight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lineEdit_outputdir = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_outputdir.setObjectName(_fromUtf8("lineEdit_outputdir"))
        self.horizontalLayout_3.addWidget(self.lineEdit_outputdir)
        self.pushButton_browseOut = QtGui.QPushButton(self.tab_2)
        self.pushButton_browseOut.setObjectName(_fromUtf8("pushButton_browseOut"))
        self.horizontalLayout_3.addWidget(self.pushButton_browseOut)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(288, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox_preset = QtGui.QComboBox(self.tab_2)
        self.comboBox_preset.setObjectName(_fromUtf8("comboBox_preset"))
        self.comboBox_preset.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_preset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.lineEdit_annotation = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_annotation.setObjectName(_fromUtf8("lineEdit_annotation"))
        self.horizontalLayout_5.addWidget(self.lineEdit_annotation)
        self.pushButton_doit = QtGui.QPushButton(self.tab_2)
        self.pushButton_doit.setObjectName(_fromUtf8("pushButton_doit"))
        self.horizontalLayout_5.addWidget(self.pushButton_doit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(20, 208, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.tabWidget)
        MainWindow_RenderBoxx.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_RenderBoxx)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow_RenderBoxx.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow_RenderBoxx)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow_RenderBoxx.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_RenderBoxx)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_RenderBoxx)

    def retranslateUi(self, MainWindow_RenderBoxx):
        MainWindow_RenderBoxx.setWindowTitle(_translate("MainWindow_RenderBoxx", "RenderBoxx_Proto", None))
        self.pushButton_add.setText(_translate("MainWindow_RenderBoxx", "Add", None))
        self.pushButton_remove.setText(_translate("MainWindow_RenderBoxx", "Remove", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow_RenderBoxx", "RenderQueue", None))
        self.label_5.setText(_translate("MainWindow_RenderBoxx", "Template Lighting", None))
        self.checkBox_useMaya.setText(_translate("MainWindow_RenderBoxx", "Use as base Maya", None))
        self.pushButton_browseLight.setText(_translate("MainWindow_RenderBoxx", ">> Browse", None))
        self.label_4.setText(_translate("MainWindow_RenderBoxx", "Output Directory", None))
        self.pushButton_browseOut.setText(_translate("MainWindow_RenderBoxx", ">> Browse", None))
        self.label_2.setText(_translate("MainWindow_RenderBoxx", "Preset", None))
        self.comboBox_preset.setItemText(0, _translate("MainWindow_RenderBoxx", "BodyScan", None))
        self.label_3.setText(_translate("MainWindow_RenderBoxx", "PDF Annotation:", None))
        self.pushButton_doit.setText(_translate("MainWindow_RenderBoxx", "** D O  I T **", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_RenderBoxx", "Process", None))

