# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbScanBoxx_UI.ui'
#
# Created: Wed Sep 18 00:32:26 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_bbScanBoxx(object):
    def setupUi(self, MainWindow_bbScanBoxx):
        MainWindow_bbScanBoxx.setObjectName(_fromUtf8("MainWindow_bbScanBoxx"))
        MainWindow_bbScanBoxx.resize(713, 334)
        self.centralwidget = QtGui.QWidget(MainWindow_bbScanBoxx)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget_master = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_master.setObjectName(_fromUtf8("tabWidget_master"))
        self.tab_project = QtGui.QWidget()
        self.tab_project.setObjectName(_fromUtf8("tab_project"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_project)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_mesh = QtGui.QRadioButton(self.tab_project)
        self.radioButton_mesh.setObjectName(_fromUtf8("radioButton_mesh"))
        self.horizontalLayout_3.addWidget(self.radioButton_mesh)
        self.radioButton_texture = QtGui.QRadioButton(self.tab_project)
        self.radioButton_texture.setObjectName(_fromUtf8("radioButton_texture"))
        self.horizontalLayout_3.addWidget(self.radioButton_texture)
        spacerItem = QtGui.QSpacerItem(298, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.treeWidget_diskMap = QtGui.QTreeWidget(self.tab_project)
        self.treeWidget_diskMap.setEnabled(False)
        self.treeWidget_diskMap.setObjectName(_fromUtf8("treeWidget_diskMap"))
        self.treeWidget_diskMap.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.treeWidget_diskMap)
        self.tabWidget_master.addTab(self.tab_project, _fromUtf8(""))
        self.tab_control = QtGui.QWidget()
        self.tab_control.setObjectName(_fromUtf8("tab_control"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_control)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.tab_control)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_subject = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_subject.setReadOnly(True)
        self.lineEdit_subject.setObjectName(_fromUtf8("lineEdit_subject"))
        self.gridLayout.addWidget(self.lineEdit_subject, 0, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.tab_control)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.lineEdit_character = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_character.setReadOnly(True)
        self.lineEdit_character.setObjectName(_fromUtf8("lineEdit_character"))
        self.gridLayout.addWidget(self.lineEdit_character, 0, 4, 1, 5)
        self.label_4 = QtGui.QLabel(self.tab_control)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 9, 1, 2)
        self.lineEdit_definition = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_definition.setReadOnly(True)
        self.lineEdit_definition.setObjectName(_fromUtf8("lineEdit_definition"))
        self.gridLayout.addWidget(self.lineEdit_definition, 0, 11, 1, 2)
        self.label_2 = QtGui.QLabel(self.tab_control)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_pose = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_pose.setObjectName(_fromUtf8("lineEdit_pose"))
        self.gridLayout.addWidget(self.lineEdit_pose, 1, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.tab_control)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.spinBox_take = QtGui.QSpinBox(self.tab_control)
        self.spinBox_take.setFrame(True)
        self.spinBox_take.setMinimum(1)
        self.spinBox_take.setObjectName(_fromUtf8("spinBox_take"))
        self.gridLayout.addWidget(self.spinBox_take, 1, 4, 1, 3)
        self.checkBox_inc = QtGui.QCheckBox(self.tab_control)
        self.checkBox_inc.setChecked(True)
        self.checkBox_inc.setObjectName(_fromUtf8("checkBox_inc"))
        self.gridLayout.addWidget(self.checkBox_inc, 1, 7, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(188, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 9, 1, 4)
        self.label_6 = QtGui.QLabel(self.tab_control)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_photoDownload = QtGui.QLineEdit(self.tab_control)
        self.lineEdit_photoDownload.setMinimumSize(QtCore.QSize(91, 0))
        self.lineEdit_photoDownload.setObjectName(_fromUtf8("lineEdit_photoDownload"))
        self.gridLayout.addWidget(self.lineEdit_photoDownload, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.checkBox_mirror = QtGui.QCheckBox(self.tab_control)
        self.checkBox_mirror.setObjectName(_fromUtf8("checkBox_mirror"))
        self.gridLayout.addWidget(self.checkBox_mirror, 2, 3, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_control)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 6, 1, 2)
        self.doubleSpinBox_focus = QtGui.QDoubleSpinBox(self.tab_control)
        self.doubleSpinBox_focus.setFrame(True)
        self.doubleSpinBox_focus.setSingleStep(0.25)
        self.doubleSpinBox_focus.setObjectName(_fromUtf8("doubleSpinBox_focus"))
        self.gridLayout.addWidget(self.doubleSpinBox_focus, 2, 8, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 10, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_control)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 11, 1, 1)
        self.doubleSpinBox_flash = QtGui.QDoubleSpinBox(self.tab_control)
        self.doubleSpinBox_flash.setFrame(True)
        self.doubleSpinBox_flash.setSingleStep(0.5)
        self.doubleSpinBox_flash.setObjectName(_fromUtf8("doubleSpinBox_flash"))
        self.gridLayout.addWidget(self.doubleSpinBox_flash, 2, 12, 1, 1)
        self.pushButton_prime = QtGui.QPushButton(self.tab_control)
        self.pushButton_prime.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_prime.setFont(font)
        self.pushButton_prime.setObjectName(_fromUtf8("pushButton_prime"))
        self.gridLayout.addWidget(self.pushButton_prime, 3, 0, 1, 7)
        self.pushButton_fire = QtGui.QPushButton(self.tab_control)
        self.pushButton_fire.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_fire.setFont(font)
        self.pushButton_fire.setObjectName(_fromUtf8("pushButton_fire"))
        self.gridLayout.addWidget(self.pushButton_fire, 3, 7, 1, 6)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.plainTextEdit_logging = QtGui.QPlainTextEdit(self.tab_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_logging.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_logging.setSizePolicy(sizePolicy)
        self.plainTextEdit_logging.setReadOnly(True)
        self.plainTextEdit_logging.setObjectName(_fromUtf8("plainTextEdit_logging"))
        self.verticalLayout_2.addWidget(self.plainTextEdit_logging)
        self.tabWidget_master.addTab(self.tab_control, _fromUtf8(""))
        self.tab_post = QtGui.QWidget()
        self.tab_post.setObjectName(_fromUtf8("tab_post"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_post)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.tab_post)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.tabWidget_master.addTab(self.tab_post, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget_master)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frame_logo = QtGui.QFrame(self.centralwidget)
        self.frame_logo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_logo.setObjectName(_fromUtf8("frame_logo"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_logo)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_logo = QtGui.QLabel(self.frame_logo)
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.horizontalLayout_4.addWidget(self.label_logo)
        self.horizontalLayout_5.addWidget(self.frame_logo)
        spacerItem5 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        MainWindow_bbScanBoxx.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_bbScanBoxx)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuNew_Session = QtGui.QMenu(self.menuFile)
        self.menuNew_Session.setObjectName(_fromUtf8("menuNew_Session"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuComms = QtGui.QMenu(self.menubar)
        self.menuComms.setObjectName(_fromUtf8("menuComms"))
        self.menuSubject = QtGui.QMenu(self.menubar)
        self.menuSubject.setObjectName(_fromUtf8("menuSubject"))
        self.menuActive_Subject = QtGui.QMenu(self.menuSubject)
        self.menuActive_Subject.setObjectName(_fromUtf8("menuActive_Subject"))
        MainWindow_bbScanBoxx.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow_bbScanBoxx)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow_bbScanBoxx.setStatusBar(self.statusbar)
        self.actionMesh = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionMesh.setObjectName(_fromUtf8("actionMesh"))
        self.actionTexture = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionTexture.setObjectName(_fromUtf8("actionTexture"))
        self.actionConfigure = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionOpen_COM1 = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionOpen_COM1.setObjectName(_fromUtf8("actionOpen_COM1"))
        self.actionCreate = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionCreate.setObjectName(_fromUtf8("actionCreate"))
        self.actionLoad = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionScanBoxx = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionScanBoxx.setObjectName(_fromUtf8("actionScanBoxx"))
        self.actionOpen_COM3 = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionOpen_COM3.setObjectName(_fromUtf8("actionOpen_COM3"))
        self.actionOpen_COM4 = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionOpen_COM4.setObjectName(_fromUtf8("actionOpen_COM4"))
        self.actionNew_Subject = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionNew_Subject.setObjectName(_fromUtf8("actionNew_Subject"))
        self.actionNew_Character = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionNew_Character.setObjectName(_fromUtf8("actionNew_Character"))
        self.actionNew_Definition = QtGui.QAction(MainWindow_bbScanBoxx)
        self.actionNew_Definition.setObjectName(_fromUtf8("actionNew_Definition"))
        self.menuNew_Session.addAction(self.actionMesh)
        self.menuNew_Session.addAction(self.actionTexture)
        self.menuFile.addAction(self.menuNew_Session.menuAction())
        self.menuAbout.addAction(self.actionScanBoxx)
        self.menuComms.addAction(self.actionOpen_COM1)
        self.menuComms.addAction(self.actionOpen_COM3)
        self.menuComms.addAction(self.actionOpen_COM4)
        self.menuActive_Subject.addAction(self.actionNew_Character)
        self.menuActive_Subject.addAction(self.actionNew_Definition)
        self.menuSubject.addAction(self.actionNew_Subject)
        self.menuSubject.addAction(self.menuActive_Subject.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuComms.menuAction())
        self.menubar.addAction(self.menuSubject.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.label.setBuddy(self.lineEdit_subject)
        self.label_3.setBuddy(self.lineEdit_character)
        self.label_4.setBuddy(self.lineEdit_definition)
        self.label_2.setBuddy(self.lineEdit_pose)
        self.label_5.setBuddy(self.spinBox_take)
        self.label_6.setBuddy(self.lineEdit_photoDownload)
        self.label_7.setBuddy(self.doubleSpinBox_focus)
        self.label_8.setBuddy(self.doubleSpinBox_flash)

        self.retranslateUi(MainWindow_bbScanBoxx)
        self.tabWidget_master.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_bbScanBoxx)

    def retranslateUi(self, MainWindow_bbScanBoxx):
        MainWindow_bbScanBoxx.setWindowTitle(_translate("MainWindow_bbScanBoxx", "ByteBoxx::SCANBOXX v1.01", None))
        self.radioButton_mesh.setText(_translate("MainWindow_bbScanBoxx", "Mesh Session", None))
        self.radioButton_texture.setText(_translate("MainWindow_bbScanBoxx", "Texture Session", None))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_project), _translate("MainWindow_bbScanBoxx", "Project Setup", None))
        self.label.setText(_translate("MainWindow_bbScanBoxx", "Subject:", None))
        self.label_3.setText(_translate("MainWindow_bbScanBoxx", "Character:", None))
        self.label_4.setText(_translate("MainWindow_bbScanBoxx", "Definition:", None))
        self.lineEdit_definition.setText(_translate("MainWindow_bbScanBoxx", "default", None))
        self.label_2.setText(_translate("MainWindow_bbScanBoxx", "Pose:", None))
        self.label_5.setText(_translate("MainWindow_bbScanBoxx", "Current Tk:", None))
        self.checkBox_inc.setText(_translate("MainWindow_bbScanBoxx", "Auto Increment", None))
        self.label_6.setText(_translate("MainWindow_bbScanBoxx", "Root:", None))
        self.checkBox_mirror.setText(_translate("MainWindow_bbScanBoxx", "Mirror Lock?", None))
        self.label_7.setText(_translate("MainWindow_bbScanBoxx", "Focus Comp (s):", None))
        self.label_8.setText(_translate("MainWindow_bbScanBoxx", "Flash Delay (ms):", None))
        self.pushButton_prime.setText(_translate("MainWindow_bbScanBoxx", "Prime Array", None))
        self.pushButton_fire.setText(_translate("MainWindow_bbScanBoxx", "&Fire Array", None))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_control), _translate("MainWindow_bbScanBoxx", "Rig Control", None))
        self.label_9.setText(_translate("MainWindow_bbScanBoxx", "Placeholder", None))
        self.tabWidget_master.setTabText(self.tabWidget_master.indexOf(self.tab_post), _translate("MainWindow_bbScanBoxx", "Post Process", None))
        self.label_logo.setText(_translate("MainWindow_bbScanBoxx", "TextLabel", None))
        self.menuFile.setTitle(_translate("MainWindow_bbScanBoxx", "File", None))
        self.menuNew_Session.setTitle(_translate("MainWindow_bbScanBoxx", "New Session", None))
        self.menuAbout.setTitle(_translate("MainWindow_bbScanBoxx", "About", None))
        self.menuComms.setTitle(_translate("MainWindow_bbScanBoxx", "Comms", None))
        self.menuSubject.setTitle(_translate("MainWindow_bbScanBoxx", "Subject", None))
        self.menuActive_Subject.setTitle(_translate("MainWindow_bbScanBoxx", "Active Subject", None))
        self.actionMesh.setText(_translate("MainWindow_bbScanBoxx", "Mesh", None))
        self.actionTexture.setText(_translate("MainWindow_bbScanBoxx", "Texture", None))
        self.actionConfigure.setText(_translate("MainWindow_bbScanBoxx", "Configure", None))
        self.actionOpen_COM1.setText(_translate("MainWindow_bbScanBoxx", "Open COM1", None))
        self.actionCreate.setText(_translate("MainWindow_bbScanBoxx", "Create", None))
        self.actionLoad.setText(_translate("MainWindow_bbScanBoxx", "Load", None))
        self.actionScanBoxx.setText(_translate("MainWindow_bbScanBoxx", "ScanBoxx", None))
        self.actionOpen_COM3.setText(_translate("MainWindow_bbScanBoxx", "Open COM3", None))
        self.actionOpen_COM4.setText(_translate("MainWindow_bbScanBoxx", "Open COM4", None))
        self.actionNew_Subject.setText(_translate("MainWindow_bbScanBoxx", "New Subject", None))
        self.actionNew_Character.setText(_translate("MainWindow_bbScanBoxx", "New Character", None))
        self.actionNew_Definition.setText(_translate("MainWindow_bbScanBoxx", "New Definition", None))

